name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint & Type Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.13

    - name: Install nox
      run: uv tool install nox --with nox-uv

    - name: Run linting
      run: nox -s lint

    - name: Run type checking
      run: nox -s type_check

  test:
    name: Test Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12', '3.13']

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install nox
      run: uv tool install nox --with nox-uv

    - name: Run tests
      run: nox -s tests --python ${{ matrix.python-version }}

    - name: Test CLI functionality
      run: nox -s cli_test

    - name: Run coverage (Ubuntu + Python 3.13 only)
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.13'
      run: nox -s coverage

    - name: Upload coverage to Codecov (Ubuntu + Python 3.13 only)
      if: matrix.os == 'ubuntu-latest' && matrix.python-version == '3.13'
      uses: codecov/codecov-action@v4
      with:
        file: ./coverage.xml
        fail_ci_if_error: false 