name: Dependencies & Security

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

jobs:
  dependency-updates:
    name: Check Dependency Updates
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.13

    - name: Install nox
      run: uv tool install nox --with nox-uv

    - name: Check for outdated dependencies
      run: |
        uv sync --group dev
        echo "Consider updating dependencies if major versions are available"

    - name: Test with latest dependencies
      run: |
        # Install with latest compatible versions
        uv sync --group dev --upgrade
        nox -s tests --python 3.13

  security-scan:
    name: Security Scanning
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        version: "latest"

    - name: Set up Python
      run: uv python install 3.13

    - name: Install security tools
      run: |
        uv tool install safety
        uv tool install bandit[toml]

    - name: Install project dependencies
      run: uv sync --group dev

    - name: Run safety check
      run: |
        uv pip freeze | safety check --json --output safety-report.json || true
        
    - name: Run bandit security scan
      run: |
        bandit -r envmcp/ -f json -o bandit-report.json || true

    - name: Upload security reports
      uses: actions/upload-artifact@v4
      with:
        name: security-reports
        path: |
          safety-report.json
          bandit-report.json 